site_name: AI / Data Development Standards
site_url: https://defra.github.io/ai-data-development-standards/
theme:
  name: material
  logo: images/favicon.png
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: blue grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - content.code.select
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
nav:
  - Home: index.md
  - Languages and Frameworks:
    - Python: languages-frameworks/python.md
    - Langchain:
      - Langchain Development: languages-frameworks/langchain/langchain-dev.md
      - LangGraph: languages-frameworks/langchain/langgraph.md
    
    - Haystack: languages-frameworks/haystack.md
  - Techniques and Models:
    - Retrieval Augmented Generation: techniques-models/rag.md
  - Tools:
    - In Review:
      - Ollama: tools/ollama.md
    - Archived:
      - LangFuse: tools/archived/langfuse.md
      - LangSmith: tools/archived/langsmith.md
  - Infrastructure:
    - Patterns: infrastructure/patterns.md
    - Azure AI Document Intelligence: infrastructure/azure-ai-document-intelligence.md
    - AWS AI Services: infrastructure/aws-ai.md
  - Guides:
    - Azure:
      - Azure AI Speech: guides/azure/ai-speech.md
      - Using Custom Data with LLMs: guides/azure/using-custom-data-with-llms.md
    - CrewAI: guides/crew-ai.md
  - Tags: tags.md
plugins:
  - glightbox
  - tags:
      tags_file: tags.md
