site_name: AI / Data Development Standards
site_url: https://defra.github.io/ai-data-development-standards/
theme:
  name: material
  logo: images/favicon.png
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: blue grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - content.code.select
markdown_extensions:
  - attr_list
  - md_in_html
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
nav:
  - Home: index.md
  - Tech Radar: tech-radar.md
  - Languages and Frameworks:
    - Python: languages-frameworks/python.md
    - Langchain:
      - Overview: languages-frameworks/langchain/langchain.md
      - LangGraph: languages-frameworks/langchain/langgraph.md
    - Haystack: languages-frameworks/haystack.md
    - CrewAI: languages-frameworks/crewai.md
  - Techniques and Models:
    - Retrieval Augmented Generation: techniques-models/rag.md
  - Tools:
    - Azure AI:
      - Content Safety: tools/azure-ai/content-safety.md
      - Responsible AI: tools/azure-ai/responsible-ai.md
      - Document Intelligence: tools/azure-ai/document-intelligence.md
    - Ollama: tools/ollama.md
    - Promptfoo: tools/promptfoo.md
    - FMEval: tools/fmeval.md
    - AutoGen Studio 2.0: tools/autogen.md
    - Archived:
      - LangFuse: tools/archived/langfuse.md
      - LangSmith: tools/archived/langsmith.md
  - Infrastructure:
    - Patterns: infrastructure/patterns.md
    - AWS AI Services: infrastructure/aws-ai.md
  - Data:
    - Data Analytics & Science Hub: data/dash.md
  - Guides:
    - Azure:
      - Azure AI Speech: guides/azure/ai-speech.md
      - Using Custom Data with LLMs: guides/azure/using-custom-data-with-llms.md
    - LangChain:      
      - LangChain Development using JavaScript: guides/langchain/javascript.md
      - LangChain Development using Python: guides/langchain/python.md
    - CrewAI: guides/crewai.md
    - Responsible AI: guides/responsible-ai.md
  - Examples:
    - Overview: examples/index.md
    - Ministerial Correspondance: examples/mcu.md
    - CFFLD Feedback Triage: examples/cffld.md
    - Data PoC: examples/data-poc.md
  - Useful Links: useful-links.md
  - Tags: tags.md
plugins:
  - glightbox
  - search
  - tags:
      tags_file: tags.md
extra_css:
  - stylesheets/extra.css
