site_name: AI / Data Development Standards
site_url: https://defra.github.io/ai-data-development-standards/
theme:
  name: material
  logo: images/favicon.png
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: blue grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - content.code.select
markdown_extensions:
  - attr_list
  - md_in_html
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
nav:
  - Home: index.md
  - Tech Radar: 
    - Overview: tech-radar/index.md
    - Languages and Frameworks:
      - Python: tech-radar/languages-frameworks/python.md
      - Langchain:
        - Overview: tech-radar/languages-frameworks/langchain/langchain.md
        - LangGraph: tech-radar/languages-frameworks/langchain/langgraph.md
      - Haystack: tech-radar/languages-frameworks/haystack.md
      - CrewAI: tech-radar/languages-frameworks/crewai.md
    - Techniques and Models:
      - Retrieval Augmented Generation: tech-radar/techniques-models/rag.md
    - Tools:
      - Azure AI:
        - Content Safety: tech-radar/tools/azure-ai/content-safety.md
        - Responsible AI: tech-radar/tools/azure-ai/responsible-ai.md
        - Document Intelligence: tech-radar/tools/azure-ai/document-intelligence.md
      - Ollama: tech-radar/tools/ollama.md
      - Promptfoo: tech-radar/tools/promptfoo.md
      - FMEval: tech-radar/tools/fmeval.md
      - AutoGen Studio 2.0: tech-radar/tools/autogen.md
      - Archived:
        - LangFuse: tech-radar/tools/archived/langfuse.md
        - LangSmith: tech-radar/tools/archived/langsmith.md
    - Infrastructure:
      - Patterns: tech-radar/infrastructure/patterns.md
      - AWS AI Services: tech-radar/infrastructure/aws-ai.md
  - Data:
    - Data Analytics & Science Hub: data/dash.md
  - Guides:
    - Azure:
      - Azure AI Speech: guides/azure/ai-speech.md
      - Using Custom Data with LLMs: guides/azure/using-custom-data-with-llms.md
    - LangChain:      
      - LangChain Development using JavaScript: guides/langchain/javascript.md
      - LangChain Development using Python: guides/langchain/python.md
    - CrewAI: guides/crewai.md
    - Responsible AI: guides/responsible-ai.md
  - Projects:
    - Overview: projects/index.md
    - Ministerial Correspondence: projects/mcu.md
    - CFFLD Feedback Triage: projects/cffld.md
    - IG Log: projects/ig-log.md
  - Useful Links: useful-links.md
  - Tags: tags.md
plugins:
  - glightbox
  - search
  - tags:
      tags_file: tags.md
extra_css:
  - stylesheets/extra.css
