name: Page Deploy

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - run: echo {github.repository}
    - uses: action/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - run: pip install mkdocs
    - run: mkdocs build
    - uses: actions/upload-artifact@v4
      with:
        name: docs
        path: ./site/
