name: Page Deploy

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - run: pip install mkdocs mkdocs-material mkdocs-glightbox
    - run: mkdocs build
    - uses: actions/upload-artifact@v4
      with:
        name: github-pages
        path: ./site/

  deploy:
    runs-on: ubuntu-22.04
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.output.page_url }}

    steps:
    - uses: actions/deploy-pages@v4
      with:
        id: deployment
